trustbloc/context

vc/examples-v1.jsonld
=> chore: Add edge-sandbox example contexts

vc/examples-v1.jsonld
=> fix: Corrected the context data

did/trustbloc-v1.jsonld
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: enable 1.0 DID context

vc/examples-ext-v1.jsonld
=> test: Correct the hierarchy of TravelCard

vc/examples-ext-v1.jsonld
=> chore: Add name and description to the examples context

vc/examples-crude-product-v1.jsonld, vc/examples-ext-v1.jsonld
=> feat: add Certified Mill Test Report & crude product credential type

vc/examples-v1.jsonld
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: add image vocab

did/trustbloc-v1.jsonld
Signed-off-by: Filip Burlacu <filip.burlacu@securekey.com>
=> fix: remove invalid publicKeyJwk term definition

vc/examples-ext-v1.jsonld
=> feat: didconnection credential context

vc/issuer-manifest-credential-v1.jsonld, vp/presentation-exchange-submission-v1.jsonld
=> feat: manifest and presentation location contexts

vc/consent-credential-v1.jsonld
=> chore: Consent Credential Context

vc/consent-credential-v1.jsonld
Split issuerDIDDoc and rpDIDDoc into did and doc attributes
=> refactor: Update CC context

vc/examples-ext-v1.jsonld
Signed-off-by: George Aristy <george.aristy@securekey.com>
=> doc: creditcard statement credential - initial version

vc/consent-credential-v1.jsonld
- Extract common element and link through type
=> refactor: Consent Credential Update

vc/authorization-credential-v1.jsonld
=> feat: AuthorizationCredential Context

vp/presentation-exchange-submission-v1.jsonld
=> feat: remove presentation location from presentation submission

vc/examples/credit-card-v1.jsonld
=> feat: CreditCardStatement json-ld context

vc/examples/driving-licence-v1.jsonld
=> chore: Drivers Licence context (basic version)

vc/examples/driving-licence-v1.jsonld
=> fix: Remove protected terms from Drivers Licence Context

vc/examples/driving-license-v1.jsonld
=> fix: Drivers License typo

governance/context.jsonld
closes #36
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
=> feat: Create Governance context

governance/context.jsonld
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
=> fix: governance context

vc/examples/driving-license-v1.jsonld, vc/examples/mDL/v1.jsonld
=> fix: Add vc name and description to the context

vc/examples/credit-score-v1.jsonld
=> chore: Credit Score jsonld context

vc/examples/driver-license-evidence-v1.jsonld
Signed-off-by: George Aristy <george.aristy@securekey.com>
=> feat: driver license evidence

vc/examples/driver-license-evidence-v1.jsonld
=> chore: Update DL Evidence context

governance/context.jsonld
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
=> chore: add GovernanceCredential type

vc/examples/citizenship-v1.jsonld
reference - https://github.com/digitalbazaar/citizenship-context/blob/master/contexts/citizenship-v1.jsonld
closes #58 
=> chore: Citizenship context

vc/authorization-credential-v1.jsonld
=> feat: AuthZ Credential - Add subjectDIDDoc

vc/examples/booking-ref-v1.jsonld
=> feat: booking ref context

vc/examples/verified-organization-v1.jsonld, vc/examples/verified-person-v1.jsonld, vc/examples/verified-relationship-v1.jsonld
Signed-off-by: david.stark <david.stark@securekey.com>
=> feat: adding json-ld for the ISED project
